server.port=8081
spring.application.name=order-service

# Porta 5433 para não conflitar com instalação local do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/ordersdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.exchange=orders.exchange
rabbitmq.queue.order-created=order.created
rabbitmq.routing-key.order-created=order.created
